name: ci workflow
on:  
  push:
    branches:
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    # services:
    #       mysql:
    #         image: mysql:8.0
    #         env:
    #           MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    #           MYSQL_DATABASE: '${DB_PASSWORD}'
    #         ports:
    #           - 33306:3306
    #         options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd
          coverage: none

      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Copy .env.example file
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Generate key
        run: php artisan key:generate

      - name: Run Migrations
        run: |
          php artisan migrate --seed

      - name: Install front-end dependencies
        run: |
          npm install
          npm run dev

      - name: Run tests
        run: php artisan test
        env:
          APP_ENV: testing

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: Logs
          path: ./storage/logs